### ISSUE TITLE
glitch with back pack

### ISSUE THREAD

**Issue by bird191** [Resonant-Rise/ResonantRiseV4#41] opened 2016-05-27 21:35 UTC
###### Mod In Question

> compact storage
###### Expected behavior

> backpack is supposed to keep inventory at all times
> ###### Actual Behavior
> 
> when he opened his backpack after getting it from his grave it was gone
###### Steps to reproduce

> Type here
###### Suggestion on how to fix or supply fix

> Type here

**Comment by Chris-Paquette** [comment] 2016-05-27 22:19
I don't know what happened. I was helping Bird with his grave, as I broke it the backpack vanished from my inventory.

**Comment by Lanse505** [comment] 2016-05-28 20:05
Currently Investigating!

**Comment by Lanse505** [comment] 2016-05-28 20:08
Can't seem to reproduce this issue o.o

**Comment by Lanse505** [comment] 2016-06-08 22:51
Can't reproduce, Closing this issue as preperation for 1.9.4 coming next week!

**Closed as completed by Lanse505** 2016-06-08 22:51 UTC
