### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Chris-Paquette** [Resonant-Rise/ResonantRiseV4#43] opened 2016-05-27 22:18 UTC
###### Mod In Question

> Builder's Guides
###### Link to crash log

> http://pastebin.com/7iMJpYHV
###### Expected behavior

> Type here
###### Actual Behavior

> I was going through a Nether portal to reach someones base, and it crashed before the world loaded. It was preventing me from logging into the server. Attempted to log in several times last night, crashed each time.
###### Steps to reproduce

> Type here
###### Suggestion on how to fix or supply fix

> Seems to somehow fixed itself but it might be worth looking into.

**Comment by Lanse505** [comment] 2016-05-28 20:08
Can't seem to reproduce this either.

**Comment by Lanse505** [comment] 2016-06-08 22:52
Not Included in 1.9.4, closing since you should be getting 1.9.4 build next week.

**Closed as completed by Lanse505** 2016-06-08 22:52 UTC
